name: This is a github action
run-name: this is a run name
on : [push]
jobs:
      test:
        runs-on: ubuntu-latest
        steps:
         - name: test
           run: sleep 1m && echo test
      build:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
          - name: build
            run: sleep 2m && echo test 
      deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
         - name: build
           run: sleep 3m && echo test
        
       

  
